# Generated by Django 4.2.23 on 2025-07-01 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermealplan',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='disease',
            name='description',
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='breakfast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakfast_meals', to='core.meal'),
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='date',
            field=models.DateField(default='2024-07-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dinner_meals', to='core.meal'),
        ),
        migrations.AddField(
            model_name='usermealplan',
            name='lunch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lunch_meals', to='core.meal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meal_plan_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='veg', max_length=10),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='core.ingredient'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='nutrition_chart',
            field=models.JSONField(),
        ),
        migrations.AlterUniqueTogether(
            name='usermealplan',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='meal',
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='usermealplan',
            name='plan_date',
        ),
    ]
